<?php
/**
 * Language Configuration
 * Supports Urdu and English
 */

// Get language from session or default to Urdu
if (!isset($_SESSION['language'])) {
    $_SESSION['language'] = 'ur'; // Default: Urdu
}

$lang = $_SESSION['language'] ?? 'ur';

// Language switching
if (isset($_GET['lang']) && in_array($_GET['lang'], ['ur', 'en'])) {
    $_SESSION['language'] = $_GET['lang'];
    $lang = $_GET['lang'];
    // Redirect to same page without lang parameter
    $redirect_url = str_replace('?lang=' . $_GET['lang'], '', $_SERVER['REQUEST_URI']);
    $redirect_url = str_replace('&lang=' . $_GET['lang'], '', $redirect_url);
    header('Location: ' . $redirect_url);
    exit;
}

// Language strings
$translations = [
    'ur' => [
        'app_name' => 'یوسف اینڈ کو',
        'app_name_en' => 'Yusuf & Co',
        'business_management_system' => 'بزنس مینجمنٹ سسٹم',
        'home' => 'ہوم',
        'dashboard' => 'ڈیش بورڈ',
        'accounts' => 'کھاتے',
        'new_account' => 'نیا کھاتہ',
        'customer_list' => 'کسٹمر لسٹ',
        'user_types' => 'یوزر ٹائپس',
        'add_user_type' => 'یوزر ٹائپ شامل کریں',
        'items' => 'جنس',
        'create_item' => 'جنس بنائیں',
        'all_items' => 'تمام جنس لسٹ',
        'purchases' => 'مال آمد',
        'add_purchase' => 'مال آمد شامل کریں',
        'all_purchases' => 'تمام مال آمد لسٹ',
        'sales' => 'مال فروخت',
        'add_sale' => 'سیل شامل کریں',
        'all_sales' => 'تمام سیل لسٹ',
        'transactions' => 'روزنامچہ',
        'debit' => 'کیش بنام',
        'credit' => 'کیش جمع',
        'journal' => 'کیش JV',
        'all_transactions' => 'تمام لین دین لسٹ',
        'reports' => 'رپورٹس',
        'party_ledger' => 'پارٹی لیجر',
        'stock_detail' => 'سٹاک کھاتہ',
        'stock_ledger' => 'سٹاک لیجر',
        'all_bills' => 'تمام بل چٹھہ',
        'stock_check' => 'مال چیک رپورٹ',
        'balance_sheet' => 'بیلنس شیٹ',
        'cash_book' => 'کیش بک',
        'daily_book' => 'روزنامچہ',
        'loan_slip' => 'قرضہ سلیپ & اگراھی',
        'users' => 'صارفین',
        'create_user' => 'نیا صارف بنائیں',
        'logout' => 'لاگ آؤٹ',
        'login' => 'لاگ ان',
        'username' => 'یوزرنیم',
        'password' => 'پاس ورڈ',
        'enter_username' => 'یوزرنیم درج کریں',
        'enter_password' => 'پاس ورڈ درج کریں',
        'search' => 'تلاش کریں',
        'date_from' => 'تاریخ سے',
        'date_to' => 'تاریخ تک',
        'check' => 'چیک کریں',
        'view' => 'دیکھیں',
        'edit' => 'ایڈٹ کریں',
        'delete' => 'حذف کریں',
        'save' => 'محفوظ کریں',
        'cancel' => 'منسوخ کریں',
        'submit' => 'جمع کروائیں',
        'add_new' => 'نیا شامل کریں',
        'name' => 'نام',
        'code' => 'کوڈ',
        'type' => 'قسم',
        'balance' => 'بیلنس',
        'status' => 'حالت',
        'active' => 'فعال',
        'inactive' => 'غیر فعال',
        'actions' => 'عمل',
        'total' => 'کل',
        'net_amount' => 'نیٹ رقم',
        'paid_amount' => 'ادائیگی',
        'balance_amount' => 'باقی',
        'date' => 'تاریخ',
        'quantity' => 'مقدار',
        'rate' => 'ریٹ',
        'amount' => 'رقم',
        'discount' => 'رعایت',
        'grand_total' => 'کل رقم',
        'supplier' => 'سپلائر',
        'customer' => 'کسٹمر',
        'item_name' => 'جنس کا نام',
        'unit' => 'یونٹ',
        'current_stock' => 'موجودہ سٹاک',
        'min_stock' => 'کم از کم سٹاک',
        'purchase_rate' => 'خرید کی قیمت',
        'sale_rate' => 'فروخت کی قیمت',
        'no_records' => 'کوئی ریکارڈ نہیں ملا',
        'select' => 'منتخب کریں',
        'required' => 'ضروری',
        'optional' => 'اختیاری',
        'phone' => 'فون',
        'mobile' => 'موبائل',
        'email' => 'ای میل',
        'address' => 'پتہ',
        'city' => 'شہر',
        'contact_person' => 'رابطہ شخص',
        'opening_balance' => 'افتتاحی بیلنس',
        'account_type' => 'کھاتہ کی قسم',
        'item_code' => 'جنس کوڈ',
        'description' => 'تفصیل',
        'narration' => 'بیان',
        'transaction_type' => 'لین دین کی قسم',
        'purchase_no' => 'خرید نمبر',
        'sale_no' => 'فروخت نمبر',
        'invoice' => 'بل',
        'bill' => 'بل',
        'party' => 'پارٹی',
        'stock' => 'سٹاک',
        'ledger' => 'لیجر',
        'report' => 'رپورٹ',
        'print' => 'پرنٹ',
        'export' => 'ایکسپورٹ',
        'filter' => 'فلٹر',
        'reset' => 'ری سیٹ',
        'close' => 'بند کریں',
        'success' => 'کامیاب',
        'error' => 'خرابی',
        'warning' => 'انتباہ',
        'info' => 'معلومات',
        'confirm' => 'تصدیق',
        'yes' => 'ہاں',
        'no' => 'نہیں',
        'loading' => 'لوڈ ہو رہا ہے',
        'please_wait' => 'براہ کرم انتظار کریں',
        'record_saved' => 'ریکارڈ محفوظ ہو گیا',
        'record_updated' => 'ریکارڈ اپ ڈیٹ ہو گیا',
        'record_deleted' => 'ریکارڈ حذف ہو گیا',
        'invalid_data' => 'غلط ڈیٹا',
        'login_failed' => 'لاگ ان ناکام',
        'access_denied' => 'رسائی مسترد',
        'page_not_found' => 'صفحہ نہیں ملا',
        'language' => 'زبان',
        'urdu' => 'اردو',
        'english' => 'English',
    ],
    'en' => [
        'app_name' => 'Yusuf & Co',
        'app_name_en' => 'Yusuf & Co',
        'business_management_system' => 'Business Management System',
        'home' => 'Home',
        'dashboard' => 'Dashboard',
        'accounts' => 'Accounts',
        'new_account' => 'New Account',
        'customer_list' => 'Customer List',
        'user_types' => 'User Types',
        'add_user_type' => 'Add User Type',
        'items' => 'Items',
        'create_item' => 'Create Item',
        'all_items' => 'All Items List',
        'purchases' => 'Purchases',
        'add_purchase' => 'Add Purchase',
        'all_purchases' => 'All Purchases List',
        'sales' => 'Sales',
        'add_sale' => 'Add Sale',
        'all_sales' => 'All Sales List',
        'transactions' => 'Transactions',
        'debit' => 'Cash Debit',
        'credit' => 'Cash Credit',
        'journal' => 'Cash JV',
        'all_transactions' => 'All Transactions List',
        'reports' => 'Reports',
        'party_ledger' => 'Party Ledger',
        'stock_detail' => 'Stock Detail',
        'stock_ledger' => 'Stock Ledger',
        'all_bills' => 'All Bills',
        'stock_check' => 'Stock Check Report',
        'balance_sheet' => 'Balance Sheet',
        'cash_book' => 'Cash Book',
        'daily_book' => 'Daily Book',
        'loan_slip' => 'Loan Slip & Ledger',
        'users' => 'Users',
        'create_user' => 'Create User',
        'logout' => 'Logout',
        'login' => 'Login',
        'username' => 'Username',
        'password' => 'Password',
        'enter_username' => 'Enter Username',
        'enter_password' => 'Enter Password',
        'search' => 'Search',
        'date_from' => 'Date From',
        'date_to' => 'Date To',
        'check' => 'Check',
        'view' => 'View',
        'edit' => 'Edit',
        'delete' => 'Delete',
        'save' => 'Save',
        'cancel' => 'Cancel',
        'submit' => 'Submit',
        'add_new' => 'Add New',
        'name' => 'Name',
        'code' => 'Code',
        'type' => 'Type',
        'balance' => 'Balance',
        'status' => 'Status',
        'active' => 'Active',
        'inactive' => 'Inactive',
        'actions' => 'Actions',
        'total' => 'Total',
        'net_amount' => 'Net Amount',
        'paid_amount' => 'Paid Amount',
        'balance_amount' => 'Balance',
        'date' => 'Date',
        'quantity' => 'Quantity',
        'rate' => 'Rate',
        'amount' => 'Amount',
        'discount' => 'Discount',
        'grand_total' => 'Grand Total',
        'supplier' => 'Supplier',
        'customer' => 'Customer',
        'item_name' => 'Item Name',
        'unit' => 'Unit',
        'current_stock' => 'Current Stock',
        'min_stock' => 'Min Stock',
        'purchase_rate' => 'Purchase Rate',
        'sale_rate' => 'Sale Rate',
        'no_records' => 'No Records Found',
        'select' => 'Select',
        'required' => 'Required',
        'optional' => 'Optional',
        'phone' => 'Phone',
        'mobile' => 'Mobile',
        'email' => 'Email',
        'address' => 'Address',
        'city' => 'City',
        'contact_person' => 'Contact Person',
        'opening_balance' => 'Opening Balance',
        'account_type' => 'Account Type',
        'item_code' => 'Item Code',
        'description' => 'Description',
        'narration' => 'Narration',
        'transaction_type' => 'Transaction Type',
        'purchase_no' => 'Purchase No',
        'sale_no' => 'Sale No',
        'invoice' => 'Invoice',
        'bill' => 'Bill',
        'party' => 'Party',
        'stock' => 'Stock',
        'ledger' => 'Ledger',
        'report' => 'Report',
        'print' => 'Print',
        'export' => 'Export',
        'filter' => 'Filter',
        'reset' => 'Reset',
        'close' => 'Close',
        'success' => 'Success',
        'error' => 'Error',
        'warning' => 'Warning',
        'info' => 'Info',
        'confirm' => 'Confirm',
        'yes' => 'Yes',
        'no' => 'No',
        'loading' => 'Loading',
        'please_wait' => 'Please Wait',
        'record_saved' => 'Record Saved',
        'record_updated' => 'Record Updated',
        'record_deleted' => 'Record Deleted',
        'invalid_data' => 'Invalid Data',
        'login_failed' => 'Login Failed',
        'access_denied' => 'Access Denied',
        'page_not_found' => 'Page Not Found',
        'language' => 'Language',
        'urdu' => 'اردو',
        'english' => 'English',
    ]
];

// Helper function to get translation
function t($key) {
    global $translations, $lang;
    return $translations[$lang][$key] ?? $key;
}

// Helper function to get current language
function getLang() {
    return $_SESSION['language'] ?? 'ur';
}

// Helper function to set language
function setLang($language) {
    if (in_array($language, ['ur', 'en'])) {
        $_SESSION['language'] = $language;
    }
}

// Helper function to get language direction
function getDir() {
    return getLang() == 'ur' ? 'rtl' : 'ltr';
}

// Helper function to get language name
function getLangName() {
    return getLang() == 'ur' ? 'اردو' : 'English';
}
?>

