<?php
/**
 * Language Configuration
 * Supports Urdu and English
 */

// Get language from session or default to Urdu
if (!isset($_SESSION['language'])) {
    $_SESSION['language'] = 'ur'; // Default: Urdu
}

$lang = $_SESSION['language'] ?? 'ur';

// Language switching
if (isset($_GET['lang']) && in_array($_GET['lang'], ['ur', 'en'])) {
    $_SESSION['language'] = $_GET['lang'];
    $lang = $_GET['lang'];
    // Redirect to same page without lang parameter
    $redirect_url = str_replace('?lang=' . $_GET['lang'], '', $_SERVER['REQUEST_URI']);
    $redirect_url = str_replace('&lang=' . $_GET['lang'], '', $redirect_url);
    header('Location: ' . $redirect_url);
    exit;
}

// Language strings
$translations = [
    'ur' => [
        'app_name' => 'یوسف اینڈ کو',
        'app_name_en' => 'Yusuf & Co',
        'business_management_system' => 'بزنس مینجمنٹ سسٹم',
        'home' => 'ہوم',
        'dashboard' => 'ڈیش بورڈ',
        'accounts' => 'کھاتے',
        'new_account' => 'نیا کھاتہ',
        'customer_list' => 'کسٹمر لسٹ',
        'user_types' => 'یوزر ٹائپس',
        'add_user_type' => 'یوزر ٹائپ شامل کریں',
        'items' => 'جنس',
        'create_item' => 'جنس بنائیں',
        'all_items' => 'تمام جنس لسٹ',
        'purchases' => 'مال آمد',
        'add_purchase' => 'مال آمد شامل کریں',
        'all_purchases' => 'تمام مال آمد لسٹ',
        'sales' => 'مال فروخت',
        'add_sale' => 'سیل شامل کریں',
        'all_sales' => 'تمام سیل لسٹ',
        'transactions' => 'روزنامچہ',
        'debit' => 'کیش بنام',
        'credit' => 'کیش جمع',
        'journal' => 'کیش JV',
        'all_transactions' => 'تمام لین دین لسٹ',
        'reports' => 'رپورٹس',
        'party_ledger' => 'پارٹی لیجر',
        'stock_detail' => 'سٹاک کھاتہ',
        'stock_ledger' => 'سٹاک لیجر',
        'all_bills' => 'تمام بل چٹھہ',
        'stock_check' => 'مال چیک رپورٹ',
        'balance_sheet' => 'بیلنس شیٹ',
        'cash_book' => 'کیش بک',
        'daily_book' => 'روزنامچہ',
        'loan_slip' => 'قرضہ سلیپ & اگراھی',
        'users' => 'صارفین',
        'create_user' => 'نیا صارف بنائیں',
        'logout' => 'لاگ آؤٹ',
        'login' => 'لاگ ان',
        'username' => 'یوزرنیم',
        'password' => 'پاس ورڈ',
        'enter_username' => 'یوزرنیم درج کریں',
        'enter_password' => 'پاس ورڈ درج کریں',
        'search' => 'تلاش کریں',
        'date_from' => 'تاریخ سے',
        'date_to' => 'تاریخ تک',
        'check' => 'چیک کریں',
        'view' => 'دیکھیں',
        'edit' => 'ایڈٹ کریں',
        'delete' => 'حذف کریں',
        'save' => 'محفوظ کریں',
        'cancel' => 'منسوخ کریں',
        'submit' => 'جمع کروائیں',
        'add_new' => 'نیا شامل کریں',
        'name' => 'نام',
        'code' => 'کوڈ',
        'type' => 'قسم',
        'balance' => 'بیلنس',
        'status' => 'حالت',
        'active' => 'فعال',
        'inactive' => 'غیر فعال',
        'actions' => 'عمل',
        'total' => 'کل',
        'net_amount' => 'نیٹ رقم',
        'paid_amount' => 'ادائیگی',
        'balance_amount' => 'باقی',
        'date' => 'تاریخ',
        'quantity' => 'مقدار',
        'rate' => 'ریٹ',
        'amount' => 'رقم',
        'discount' => 'رعایت',
        'grand_total' => 'کل رقم',
        'supplier' => 'سپلائر',
        'customer' => 'کسٹمر',
        'item_name' => 'جنس کا نام',
        'unit' => 'یونٹ',
        'current_stock' => 'موجودہ سٹاک',
        'min_stock' => 'کم از کم سٹاک',
        'purchase_rate' => 'خرید کی قیمت',
        'sale_rate' => 'فروخت کی قیمت',
        'no_records' => 'کوئی ریکارڈ نہیں ملا',
        'select' => 'منتخب کریں',
        'required' => 'ضروری',
        'optional' => 'اختیاری',
        'phone' => 'فون',
        'mobile' => 'موبائل',
        'email' => 'ای میل',
        'address' => 'پتہ',
        'city' => 'شہر',
        'contact_person' => 'رابطہ شخص',
        'opening_balance' => 'افتتاحی بیلنس',
        'account_type' => 'کھاتہ کی قسم',
        'item_code' => 'جنس کوڈ',
        'description' => 'تفصیل',
        'narration' => 'بیان',
        'transaction_type' => 'لین دین کی قسم',
        'purchase_no' => 'خرید نمبر',
        'sale_no' => 'فروخت نمبر',
        'invoice' => 'بل',
        'bill' => 'بل',
        'party' => 'پارٹی',
        'stock' => 'سٹاک',
        'ledger' => 'لیجر',
        'report' => 'رپورٹ',
        'print' => 'پرنٹ',
        'export' => 'ایکسپورٹ',
        'filter' => 'فلٹر',
        'reset' => 'ری سیٹ',
        'close' => 'بند کریں',
        'success' => 'کامیاب',
        'error' => 'خرابی',
        'warning' => 'انتباہ',
        'info' => 'معلومات',
        'confirm' => 'تصدیق',
        'yes' => 'ہاں',
        'no' => 'نہیں',
        'loading' => 'لوڈ ہو رہا ہے',
        'please_wait' => 'براہ کرم انتظار کریں',
        'record_saved' => 'ریکارڈ محفوظ ہو گیا',
        'record_updated' => 'ریکارڈ اپ ڈیٹ ہو گیا',
        'record_deleted' => 'ریکارڈ حذف ہو گیا',
        'invalid_data' => 'غلط ڈیٹا',
        'login_failed' => 'لاگ ان ناکام',
        'access_denied' => 'رسائی مسترد',
        'page_not_found' => 'صفحہ نہیں ملا',
        'language' => 'زبان',
        'urdu' => 'اردو',
        'english' => 'English',
        'account_info' => 'کھاتہ کی معلومات',
        'item_info' => 'جنس کی معلومات',
        'purchase_info' => 'خرید کی معلومات',
        'sale_info' => 'فروخت کی معلومات',
        'transaction_info' => 'لین دین کی معلومات',
        'back' => 'واپس',
        'previous' => 'پچھلا',
        'next' => 'اگلا',
        'remarks' => 'ریمارکس',
        'category' => 'قسم',
        'opening_stock' => 'افتتاحی سٹاک',
        'bill_no' => 'بل نمبر',
        'details' => 'تفصیلات',
        'basic_info' => 'بنیادی معلومات',
        'account_code' => 'کھاتہ کوڈ',
        'total_purchased' => 'کل خرید',
        'total_sold' => 'کل فروخت',
        'opening_debit_balance' => 'افتتاحی ڈیبٹ بیلنس',
        'purchase_balance' => 'خرید کا بیلنس',
        'assets' => 'جائیداد',
        'liabilities' => 'ذمہ داریاں',
        'net_worth' => 'خالص مالیت',
        'opening_balance_label' => 'افتتاحی بیلنس',
        'cash_debit' => 'کیش بنام',
        'cash_credit' => 'کیش جمع',
        'balance' => 'بیلنس',
        'reference' => 'حوالہ',
        'no_transactions_period' => 'اس مدت میں کوئی لین دین نہیں ملا',
        'system_overview' => 'سیسٹم کا جائزہ',
        'quick_links' => 'فوری لنکس',
        'all_accounts_label' => 'کل کھاتے',
        'all_items_label' => 'کل جنس',
        'low_stock_label' => 'کم سٹاک',
        'debit_amount' => 'ڈیبٹ رقم',
        'credit_amount' => 'کریڈٹ رقم',
        'select_account' => 'اکاؤنٹ منتخب کریں',
        'select_item' => 'جنس منتخب کریں',
        'select_supplier' => 'سپلائر منتخب کریں',
        'select_customer' => 'کسٹمر منتخب کریں',
        'enter_amount' => 'رقم درج کریں',
        'enter_narration' => 'بیان درج کریں',
        'please_select_account' => 'براہ کرم اکاؤنٹ منتخب کریں',
        'please_enter_amount' => 'رقم درست درج کریں',
        'please_select_supplier' => 'براہ کرم سپلائر منتخب کریں',
        'please_select_customer' => 'براہ کرم کسٹمر منتخب کریں',
        'please_add_item' => 'براہ کرم کم از کم ایک جنس شامل کریں',
        'please_enter_item_details' => 'براہ کرم جنس کی تفصیلات درج کریں',
        'please_enter_account_name' => 'براہ کرم کھاتہ کا نام درج کریں',
        'please_enter_item_name' => 'براہ کرم جنس کا نام درج کریں',
        'account_added_success' => 'کھاتہ کامیابی سے شامل ہو گیا',
        'account_updated_success' => 'کھاتہ کامیابی سے اپ ڈیٹ ہو گیا',
        'item_added_success' => 'جنس کامیابی سے شامل ہو گئی',
        'item_updated_success' => 'جنس کامیابی سے اپ ڈیٹ ہو گئی',
        'purchase_added_success' => 'خرید کامیابی سے شامل ہو گئی',
        'sale_added_success' => 'فروخت کامیابی سے شامل ہو گئی',
        'transaction_recorded_success' => 'لین دین کامیابی سے ریکارڈ ہو گیا',
        'journal_voucher_success' => 'جرنل واؤچر کامیابی سے ریکارڈ ہو گیا',
        'error_adding_account' => 'کھاتہ شامل کرنے میں خرابی',
        'error_updating_account' => 'کھاتہ اپ ڈیٹ کرنے میں خرابی',
        'error_adding_item' => 'جنس شامل کرنے میں خرابی',
        'error_updating_item' => 'جنس اپ ڈیٹ کرنے میں خرابی',
        'error_recording_transaction' => 'لین دین ریکارڈ کرنے میں خرابی',
        'error_recording_journal' => 'جرنل واؤچر ریکارڈ کرنے میں خرابی',
        'item_not_found' => 'جنس نہیں ملی',
        'insufficient_stock' => 'کا سٹاک ناکافی ہے',
        'both_accounts_required' => 'براہ کرم دونوں اکاؤنٹس منتخب کریں',
        'accounts_cannot_same' => 'ڈیبٹ اور کریڈٹ اکاؤنٹ ایک جیسے نہیں ہو سکتے',
        'type_name_required' => 'براہ کرم ٹائپ کا نام درج کریں',
        'type_already_exists' => 'یہ ٹائپ پہلے سے موجود ہے',
        'user_type_added_success' => 'یوزر ٹائپ کامیابی سے شامل ہو گیا',
        'error_adding_user_type' => 'یوزر ٹائپ شامل کرنے میں خرابی',
        'username_password_required' => 'براہ کرم یوزرنیم اور پاس ورڈ درج کریں',
        'passwords_not_match' => 'پاس ورڈز میل نہیں کھاتے',
        'password_min_length' => 'پاس ورڈ کم از کم 6 حروف کا ہونا چاہیے',
        'username_exists' => 'یہ یوزرنیم پہلے سے موجود ہے',
        'user_created_success' => 'صارف کامیابی سے بنایا گیا',
        'error_creating_user' => 'صارف بنانے میں خرابی',
        'all_items_label_table' => 'تمام جنس',
        'all_accounts_label_table' => 'تمام کھاتے',
        'all_purchases_label' => 'تمام خرید',
        'all_sales_label' => 'تمام فروخت',
        'all_transactions_label' => 'تمام لین دین',
        'stock_detail_all_items' => 'تمام جنس کی سٹاک تفصیلات',
        'cash_book_report' => 'کیش بک رپورٹ',
        'daily_book_report' => 'روزنامچہ رپورٹ',
        'balance_sheet_report' => 'بیلنس شیٹ',
        'party_ledger_report' => 'پارٹی لیجر',
        'stock_ledger_report' => 'سٹاک لیجر',
        'view_report' => 'دیکھیں',
        'as_on_date' => 'تاریخ تک',
        'debit' => 'ڈیبٹ',
        'credit' => 'کریڈٹ',
        'type_name_english' => 'ٹائپ کا نام (انگریزی)',
        'type_name_urdu_label' => 'ٹائپ کا نام (اردو)',
        'user_info' => 'صارف کی معلومات',
        'full_name' => 'پورا نام',
        'confirm_password' => 'پاس ورڈ کی تصدیق',
        'user_type_label' => 'یوزر کی قسم',
    ],
    'en' => [
        'app_name' => 'Yusuf & Co',
        'app_name_en' => 'Yusuf & Co',
        'business_management_system' => 'Business Management System',
        'home' => 'Home',
        'dashboard' => 'Dashboard',
        'accounts' => 'Accounts',
        'new_account' => 'New Account',
        'customer_list' => 'Customer List',
        'user_types' => 'User Types',
        'add_user_type' => 'Add User Type',
        'items' => 'Items',
        'create_item' => 'Create Item',
        'all_items' => 'All Items List',
        'purchases' => 'Purchases',
        'add_purchase' => 'Add Purchase',
        'all_purchases' => 'All Purchases List',
        'sales' => 'Sales',
        'add_sale' => 'Add Sale',
        'all_sales' => 'All Sales List',
        'transactions' => 'Transactions',
        'debit' => 'Cash Debit',
        'credit' => 'Cash Credit',
        'journal' => 'Cash JV',
        'all_transactions' => 'All Transactions List',
        'reports' => 'Reports',
        'party_ledger' => 'Party Ledger',
        'stock_detail' => 'Stock Detail',
        'stock_ledger' => 'Stock Ledger',
        'all_bills' => 'All Bills',
        'stock_check' => 'Stock Check Report',
        'balance_sheet' => 'Balance Sheet',
        'cash_book' => 'Cash Book',
        'daily_book' => 'Daily Book',
        'loan_slip' => 'Loan Slip & Ledger',
        'users' => 'Users',
        'create_user' => 'Create User',
        'logout' => 'Logout',
        'login' => 'Login',
        'username' => 'Username',
        'password' => 'Password',
        'enter_username' => 'Enter Username',
        'enter_password' => 'Enter Password',
        'search' => 'Search',
        'date_from' => 'Date From',
        'date_to' => 'Date To',
        'check' => 'Check',
        'view' => 'View',
        'edit' => 'Edit',
        'delete' => 'Delete',
        'save' => 'Save',
        'cancel' => 'Cancel',
        'submit' => 'Submit',
        'add_new' => 'Add New',
        'name' => 'Name',
        'code' => 'Code',
        'type' => 'Type',
        'balance' => 'Balance',
        'status' => 'Status',
        'active' => 'Active',
        'inactive' => 'Inactive',
        'actions' => 'Actions',
        'total' => 'Total',
        'net_amount' => 'Net Amount',
        'paid_amount' => 'Paid Amount',
        'balance_amount' => 'Balance',
        'date' => 'Date',
        'quantity' => 'Quantity',
        'rate' => 'Rate',
        'amount' => 'Amount',
        'discount' => 'Discount',
        'grand_total' => 'Grand Total',
        'supplier' => 'Supplier',
        'customer' => 'Customer',
        'item_name' => 'Item Name',
        'unit' => 'Unit',
        'current_stock' => 'Current Stock',
        'min_stock' => 'Min Stock',
        'purchase_rate' => 'Purchase Rate',
        'sale_rate' => 'Sale Rate',
        'no_records' => 'No Records Found',
        'select' => 'Select',
        'required' => 'Required',
        'optional' => 'Optional',
        'phone' => 'Phone',
        'mobile' => 'Mobile',
        'email' => 'Email',
        'address' => 'Address',
        'city' => 'City',
        'contact_person' => 'Contact Person',
        'opening_balance' => 'Opening Balance',
        'account_type' => 'Account Type',
        'item_code' => 'Item Code',
        'description' => 'Description',
        'narration' => 'Narration',
        'transaction_type' => 'Transaction Type',
        'purchase_no' => 'Purchase No',
        'sale_no' => 'Sale No',
        'invoice' => 'Invoice',
        'bill' => 'Bill',
        'party' => 'Party',
        'stock' => 'Stock',
        'ledger' => 'Ledger',
        'report' => 'Report',
        'print' => 'Print',
        'export' => 'Export',
        'filter' => 'Filter',
        'reset' => 'Reset',
        'close' => 'Close',
        'success' => 'Success',
        'error' => 'Error',
        'warning' => 'Warning',
        'info' => 'Info',
        'confirm' => 'Confirm',
        'yes' => 'Yes',
        'no' => 'No',
        'loading' => 'Loading',
        'please_wait' => 'Please Wait',
        'record_saved' => 'Record Saved',
        'record_updated' => 'Record Updated',
        'record_deleted' => 'Record Deleted',
        'invalid_data' => 'Invalid Data',
        'login_failed' => 'Login Failed',
        'access_denied' => 'Access Denied',
        'page_not_found' => 'Page Not Found',
        'language' => 'Language',
        'urdu' => 'اردو',
        'english' => 'English',
        'account_info' => 'Account Information',
        'item_info' => 'Item Information',
        'purchase_info' => 'Purchase Information',
        'sale_info' => 'Sale Information',
        'transaction_info' => 'Transaction Information',
        'back' => 'Back',
        'previous' => 'Previous',
        'next' => 'Next',
        'remarks' => 'Remarks',
        'category' => 'Category',
        'opening_stock' => 'Opening Stock',
        'bill_no' => 'Bill No',
        'details' => 'Details',
        'basic_info' => 'Basic Information',
        'account_code' => 'Account Code',
        'total_purchased' => 'Total Purchased',
        'total_sold' => 'Total Sold',
        'opening_debit_balance' => 'Opening Debit Balance',
        'purchase_balance' => 'Purchase Balance',
        'assets' => 'Assets',
        'liabilities' => 'Liabilities',
        'net_worth' => 'Net Worth',
        'opening_balance_label' => 'Opening Balance',
        'cash_debit' => 'Cash Debit',
        'cash_credit' => 'Cash Credit',
        'balance' => 'Balance',
        'reference' => 'Reference',
        'no_transactions_period' => 'No transactions found for this period',
        'system_overview' => 'System Overview',
        'quick_links' => 'Quick Links',
        'all_accounts_label' => 'Total Accounts',
        'all_items_label' => 'Total Items',
        'low_stock_label' => 'Low Stock',
        'debit_amount' => 'Debit Amount',
        'credit_amount' => 'Credit Amount',
        'select_account' => 'Select Account',
        'select_item' => 'Select Item',
        'select_supplier' => 'Select Supplier',
        'select_customer' => 'Select Customer',
        'enter_amount' => 'Enter Amount',
        'enter_narration' => 'Enter Narration',
        'please_select_account' => 'Please select account',
        'please_enter_amount' => 'Please enter valid amount',
        'please_select_supplier' => 'Please select supplier',
        'please_select_customer' => 'Please select customer',
        'please_add_item' => 'Please add at least one item',
        'please_enter_item_details' => 'Please enter item details',
        'please_enter_account_name' => 'Please enter account name',
        'please_enter_item_name' => 'Please enter item name',
        'account_added_success' => 'Account added successfully',
        'account_updated_success' => 'Account updated successfully',
        'item_added_success' => 'Item added successfully',
        'item_updated_success' => 'Item updated successfully',
        'purchase_added_success' => 'Purchase added successfully',
        'sale_added_success' => 'Sale added successfully',
        'transaction_recorded_success' => 'Transaction recorded successfully',
        'journal_voucher_success' => 'Journal voucher recorded successfully',
        'error_adding_account' => 'Error adding account',
        'error_updating_account' => 'Error updating account',
        'error_adding_item' => 'Error adding item',
        'error_updating_item' => 'Error updating item',
        'error_recording_transaction' => 'Error recording transaction',
        'error_recording_journal' => 'Error recording journal voucher',
        'item_not_found' => 'Item not found',
        'insufficient_stock' => 'has insufficient stock',
        'both_accounts_required' => 'Please select both accounts',
        'accounts_cannot_same' => 'Debit and Credit accounts cannot be same',
        'type_name_required' => 'Please enter type name',
        'type_already_exists' => 'This type already exists',
        'user_type_added_success' => 'User type added successfully',
        'error_adding_user_type' => 'Error adding user type',
        'username_password_required' => 'Please enter username and password',
        'passwords_not_match' => 'Passwords do not match',
        'password_min_length' => 'Password must be at least 6 characters',
        'username_exists' => 'Username already exists',
        'user_created_success' => 'User created successfully',
        'error_creating_user' => 'Error creating user',
        'all_items_label_table' => 'All Items',
        'all_accounts_label_table' => 'All Accounts',
        'all_purchases_label' => 'All Purchases',
        'all_sales_label' => 'All Sales',
        'all_transactions_label' => 'All Transactions',
        'stock_detail_all_items' => 'Stock Details of All Items',
        'cash_book_report' => 'Cash Book Report',
        'daily_book_report' => 'Daily Book Report',
        'balance_sheet_report' => 'Balance Sheet',
        'party_ledger_report' => 'Party Ledger',
        'stock_ledger_report' => 'Stock Ledger',
        'view_report' => 'View',
        'as_on_date' => 'As On Date',
        'debit' => 'Debit',
        'credit' => 'Credit',
        'type_name_english' => 'Type Name (English)',
        'type_name_urdu_label' => 'Type Name (Urdu)',
        'user_info' => 'User Information',
        'full_name' => 'Full Name',
        'confirm_password' => 'Confirm Password',
        'user_type_label' => 'User Type',
    ]
];

// Helper function to get translation
function t($key) {
    global $translations, $lang;
    return $translations[$lang][$key] ?? $key;
}

// Helper function to get current language
function getLang() {
    return $_SESSION['language'] ?? 'ur';
}

// Helper function to set language
function setLang($language) {
    if (in_array($language, ['ur', 'en'])) {
        $_SESSION['language'] = $language;
    }
}

// Helper function to get language direction
function getDir() {
    return getLang() == 'ur' ? 'rtl' : 'ltr';
}

// Helper function to get language name
function getLangName() {
    return getLang() == 'ur' ? 'اردو' : 'English';
}
?>

